"""Action icon frames — GENERATED by scripts/build_action_frames.py.

Each concept maps to an ordered list of codepoints. A single-entry list
is a static icon; a longer one is an animation, in frame order. Swap the
codepoint in the cell on a timer to animate — the terminal redraws one
character, which costs nothing.

Built at cell widths 2 and 3: the N-cell variant lives at codepoint +
N*0x100, and needs N-1 trailing spaces to reserve the columns its bitmap
has already painted into.
"""
from __future__ import annotations

WIDTHS = (2, 3)

FRAMES: dict[str, list[int]] = {
    "search": [0xE900, 0xE901, 0xE902, 0xE903, 0xE904, 0xE905, 0xE906, 0xE907, 0xE908, 0xE909, 0xE90A, 0xE90B],
    "db-research": [0xE90C, 0xE90D, 0xE90E, 0xE90F, 0xE910, 0xE911],
    "net-research": [0xE912],
    "deep-research": [0xE913],
    "rag": [0xE914],
    "rerank": [0xE915],
    "read": [0xE916, 0xE917, 0xE918, 0xE919, 0xE91A, 0xE91B],
    "write": [0xE91C, 0xE91D, 0xE91E, 0xE91F, 0xE920, 0xE921, 0xE922, 0xE923, 0xE924, 0xE925, 0xE926, 0xE927, 0xE928, 0xE929, 0xE92A, 0xE92B, 0xE92C, 0xE92D, 0xE92E, 0xE92F, 0xE930, 0xE931],
    "think": [0xE932, 0xE933, 0xE934, 0xE935, 0xE936],
    "message": [0xE937],
    "user-message": [0xE938],
    "user-press": [0xE939, 0xE93A, 0xE93B],
    "instruction": [0xE93C],
    "template": [0xE93D, 0xE93E, 0xE93F, 0xE940, 0xE941, 0xE942, 0xE943, 0xE944, 0xE945],
}


def frame(concept: str, i: int = 0, cells: int = 2) -> str:
    """One frame as a string of exactly `cells` columns."""
    cps = FRAMES.get(concept)
    if not cps:
        return " " * cells
    cp = cps[i % len(cps)]
    return chr(cp + cells * 0x100) + " " * (cells - 1)


def count(concept: str) -> int:
    """How many frames a concept has. 1 means it is static."""
    return len(FRAMES.get(concept, ()))
